### ISSUE TITLE
Lacking tinyint support

### ISSUE THREAD

**Issue by CheckeredFlag** [bizley/yii2-migration#19]
The lack of support for `tinyint` that was introduced in Yii 2.0.14 results in an improper column definition:
```php
'flag' => $this->unsigned()->notNull()->defaultValue('0'),
```
instead of:
```php
'flag' => $this->tinyInteger(1)->unsigned()->notNull()->defaultValue('0'),
```
Since `$this` is a `Migration` object, the `ColumnSchemaBuilder` methods that follow (e.g. `unsigned()`) result in an error.

Seems that when encountering an unexpected column type, either the column should be skipped altogether or use a default column generator method such as?
```php
'foo' => $this->integer()->comment('ERROR: Unexpected column type: foobar'),
```
Perhaps better to address in a separate issue.

**Comment by bizley** [comment]
Thank you for this PR, I'm working on new version of this package that will support indexes thanks to 2.0.13 changes and haven't got time to add new features from 2.0.14 yet.

Could you prepare another PR fixing BC problem you mentioned? I think it's better to return error message in case the unrecognized column type has been detected instead of falling back to `integer`

**Comment by CheckeredFlag** [comment]
I'll work on a PR when I get a few tuits.
