### ISSUE TITLE
What about Views?

### ISSUE THREAD

**Issue by Isan26** [bizley/yii2-migration#47]
Is there is a way for automate the generation of VIEWS, my DB have 3 VIEWS and the extension reads them as tables, so when i run the migrations on a fresh DB i wont have the views but instead will have tables with the same names...

**Comment by bizley** [comment]
Currently Yii does not support views in migration so this extension can not do it as well. The only thing I can recommend is to generate migrations manually and to add their names to `skipMigrations` array.

The problem is that creating or updating all the tables tries to use such views as well. That gives me the idea to add option to exclude selected tables from that mass action.
