### ISSUE TITLE
MySQL MEDIUMBLOB represents as string()

### ISSUE THREAD

**Issue by tsvetiligo** [bizley/yii2-migration#90]
MySQL BLOB represents as binary(), but MEDIUMBLOB represents as string().
addColumn() 'MEDIUMBLOB' throw error "Column data must be provided as an instance of yii\db\ColumnSchemaBuilder".

**Comment by bizley** [comment]
As it is written in readme:

> Updating migrations process requires for methods createTable(), addColumn(), and alterColumn() to provide changes in columns definition in form of an instance of yii\db\ColumnSchemaBuilder (like $this->string() instead of 'varchar(255)').

**Comment by tsvetiligo** [comment]
I'm sorry but I don't understand witch propped way to define MEDIUMBLOB.

**Comment by bizley** [comment]
If I'm not mistaken you can try `->binary(16777216)` since MEDIUMBLOB is up to 16 MB.

**Comment by tsvetiligo** [comment]
> If I'm not mistaken you can try `->binary(16777216)` since MEDIUMBLOB is up to 16 MB.

I already tried this and get BLOB in table.

**Comment by bizley** [comment]
Is your database engine supports mediumblob at all? If so, do you need exactly mediumblob instead of just blob? If again so - I'm afraid there is not much more I can do, yii2-migration works on ColumnSchemaBuilder columns definitions only. If you would like to make it work with pure SQL definitions I would love to take your PR.
